### ISSUE TITLE
Program hangs and do not close if we use println! inside enable/disable tracking section without calling println before.

### ISSUE THREAD

**Issue by NicolasVidal** [tobz/tracking-allocator#10]
Here is a simple snippet showing the issue : 

```rust
use std::alloc::System;

#[allow(unused)]
use tracking_allocator::{
    AllocationGroupId, AllocationRegistry, AllocationTracker, Allocator,
};

#[global_allocator]
static GLOBAL: Allocator<System> = tracking_allocator::Allocator::system();

struct StdoutTracker;

impl AllocationTracker for StdoutTracker {
    fn allocated(
        &self,
        addr: usize,
        object_size: usize,
        wrapped_size: usize,
        group_id: AllocationGroupId,
    ) {
        println!(
            "allocation -> addr=0x{:0x} object_size={} wrapped_size={} group_id={:?}",
            addr, object_size, wrapped_size, group_id
        );
    }

    fn deallocated(
        &self,
        addr: usize,
        object_size: usize,
        wrapped_size: usize,
        source_group_id: AllocationGroupId,
        current_group_id: AllocationGroupId,
    ) {
        println!(
            "deallocation -> addr=0x{:0x} object_size={} wrapped_size={} source_group_id={:?} current_group_id={:?}",
            addr, object_size, wrapped_size, source_group_id, current_group_id
        );
    }
}

fn main() {
    AllocationRegistry::set_global_tracker(StdoutTracker)
        .expect("no other global tracker should be set yet");

    // Uncomment this line to see the difference
    // println!("There will be no issue if this line is commented out");

    AllocationRegistry::enable_tracking();

    println!("Will you see me ?");

    AllocationRegistry::disable_tracking();
}
```

Observed behaviour : 
- program never ends
- "Will you see me ?" is never printed

If we uncomment the previous println! :
- program ends
- "Will you see me ?" is printed

This issue has been reproduced in Rust 1.68.2 on Windows and Linux.

**Comment by fasterthanlime** [comment]
(Note: you can add "rust" after the triple-backquote to get syntax highlighting, see https://gist.github.com/fasterthanlime/ccc2cf1d9ece537ac53ee013d1a312d1)

**Comment by NicolasVidal** [comment]
Thanks for the tip :)

**Comment by tobz** [comment]
I suspect this is related to a deadlock with how stdout/stderr are handled in terms of life before/after `main`: there's some locking that happens, IIRC, for accessing stdio.  Ultimately, I ended up forking this code for work (which was the reason I originally created it in the first place) and we don't call `println!` within the allocation tracking path.

I'd be open to PRs fixing the particular `println!` example, and/or code comments that explain the pitfalls, but personally, I think of this repository/crate as read-only/archived.  Life has been busy and nobody ever really asks me about it, though, so I never went through with actually marking it as archived. :P
